package org.apiminer.entities;

public enum LogType {
	PAGE_REQUEST, 
	BTN_EXAMPLE_CLICK,
	PATTERNS_LIST_CLICK,
	USAGE_PATTERN_FILTER,
	EXAMPLE_REQUEST,
	PATTERN_REQUEST,
	FULL_CODE_REQUEST,
	EXAMPLE_FEEDBACK;
}
